# AI ArticleManager/docker-compose.yml

services:
  api:
    build:
      context: .  # Refers to the Dockerfile in the root directory
    container_name: fastapi_app
    ports:
      - "8000:8000"  # Expose FastAPI's port on localhost
    environment:
      - MONGO_URI=mongodb+srv://dev:DJgMpxz8oXvLN0ma@article-management.pcflq.mongodb.net/?retryWrites=true&w=majority&appName=article-management
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend  # Path to Next.js Dockerfile
    container_name: nextjs_frontend
    ports:
      - "3000:3000"  # Expose Next.js on localhost
    depends_on:
      - api  # Ensure backend starts before frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8000  # Connect to FastAPI via internal Docker network
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
